CREATE TABLE Users(
    Id UUID NOT NULL PRIMARY KEY,
    Email VARCHAR(70) NOT NULL UNIQUE,
    TaxNumber VARCHAR(15) NOT NULL UNIQUE,
    FullName VARCHA(70) NOT NULL,
    Type VARCHAR(30) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateAt DATETIME 
);